source 'https://rubygems.org'

gem 'money', '6.0.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.4'

# Use sqlite3 as the database for Active Record
gem 'sqlite3'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.2'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end


gem 'bootstrap-sass', '~> 3.1.1'
gem 'faraday'
gem 'faraday_middleware'
gem 'ruby-hmac'
gem 'rack-cors', :require => 'rack/cors'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
end
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'net-sftp'
gem 'net-ssh'
gem 'net-scp'

gem 'json'

gem 'spree', '2.2.1'
gem 'spree_gateway', :git => 'http://github.com/spree/spree_gateway.git', :branch => '2-2-stable'
gem 'spree_auth_devise', :git => 'http://github.com/spree/spree_auth_devise.git', :branch => '2-2-stable'


gem "httparty"
gem 'rest-client', '~> 1.6.7'

#Dropbox gem
gem 'dropbox-sdk'

#To mongo database
gem 'mongo'
gem 'bson_ext'

#To automatic task
gem 'whenever', :require => false

#To connection with google drive
gem 'google_drive'

gem 'twitter'

#To read microsoft access
#gem 'mdb'

#To use rabbitmq
#https://marcqualie.com/2012/12/install-rabbitmq-on-ubuntu-12.04
#http://rubybunny.info/articles/getting_started.html
gem "bunny"


#To use jarfile

#https://paulschreiber.com/blog/2010/08/07/howto-install-the-rjb-gem-on-ubuntu-and-mac-os-x/
#https://github.com/mguymon/lock_jar
#gem 'rjb'
#gem 'lock_jar'

#gem 'naether'
